"""Event-driven contextual handler — processes any home event through SENSE-THINK-ACT-EXPLAIN.

Implements a generic event handler that uses the full cognitive pipeline
to respond to any detected event without scenario-specific logic.

Requirements:
    7.1: Process EventBridge events within 5 seconds
    7.3: Critical events trigger immediate context fusion
    10.1: Every action accompanied by explanation
    13.1: Handle power cut through general-purpose logic
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.context.engine import ContextEngine
from src.intelligence.engine import ProactiveEngine
from src.models.intelligence import ActionPlan
from src.devices.base import DeviceAdapter
from src.utils.logging import get_logger

logger = get_logger(__name__)

# Events that require immediate processing with forced context refresh
CRITICAL_EVENTS = {"power_cut", "security_breach", "device_failure", "fire_alarm"}


class ContextualEventHandler:
    """Generic event-driven handler that processes any home event
    using contextual reasoning. No scenario-specific logic.

    Implements the full SENSE-THINK-ACT-EXPLAIN pipeline for events.

    Attributes:
        _context: ContextEngine for building context snapshots.
        _proactive: ProactiveEngine for reasoning about events.
        _devices: Optional mapping of device_id to DeviceAdapter for action execution.
    """

    def __init__(
        self,
        context_engine: ContextEngine,
        proactive_engine: ProactiveEngine,
        device_adapters: Optional[Dict[str, DeviceAdapter]] = None,
    ):
        """Initialize the event handler with required engines.

        Args:
            context_engine: Engine for building context snapshots.
            proactive_engine: Engine for reasoning and action planning.
            device_adapters: Optional mapping of device_id to adapter for execution.
        """
        self._context = context_engine
        self._proactive = proactive_engine
        self._devices = device_adapters or {}

    def handle_event(self, event: Dict[str, Any]) -> Dict[str, Any]:
        """Process any detected event through the cognitive pipeline.

        SENSE: Gather full context at the moment of the event.
               Critical events force an immediate context refresh.
        THINK: Invoke reasoning with event + context to produce an action plan.
        ACT:   Execute approved actions from the plan (respecting autonomy).
        EXPLAIN: Generate explanation from the reasoning chain.

        Args:
            event: Dict with at minimum "event_type" and optional
                   "source", "details", "event_id".

        Returns:
            Dict with keys:
                - event_type: The type of event handled.
                - is_critical: Whether the event was classified as critical.
                - plan: The ActionPlan generated by reasoning.
                - actions_executed: List of action dicts from the plan.
                - explanation: The reasoning chain explaining decisions.
                - timestamp: ISO timestamp of when handling completed.
        """
        event_type = event.get("event_type", "unknown")
        is_critical = self.is_critical_event(event)

        logger.info(f"Handling event: {event_type} (critical={is_critical})")

        # SENSE: Force refresh context for critical events
        snapshot = self._context.build_snapshot(force_refresh=is_critical)

        # THINK: Invoke reasoning through proactive engine
        plan = self._proactive.handle_event(event, snapshot=snapshot)

        # ACT: Execute actions from the plan
        actions_executed = self._execute_actions(plan)

        # EXPLAIN: The explanation comes from the reasoning chain
        explanation = plan.reasoning_chain

        result = {
            "event_type": event_type,
            "is_critical": is_critical,
            "plan": plan,
            "actions_executed": actions_executed,
            "explanation": explanation,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        logger.info(
            f"Event {event_type} handled: {len(actions_executed)} actions, "
            f"critical={is_critical}"
        )

        return result

    def is_critical_event(self, event: Dict[str, Any]) -> bool:
        """Check if an event is critical and needs immediate processing.

        Critical events bypass the context cache and force a fresh
        context snapshot to ensure decisions are based on real-time state.

        Args:
            event: Event dictionary with at minimum "event_type".

        Returns:
            True if the event is classified as critical.
        """
        return event.get("event_type", "") in CRITICAL_EVENTS

    def _execute_actions(self, plan: ActionPlan) -> List[Dict[str, Any]]:
        """Extract and execute actions from the action plan.

        Iterates through all predictions in the plan and builds
        a summary of actions to execute. In a full implementation,
        this would check autonomy permissions and invoke device adapters.

        Args:
            plan: The ActionPlan produced by the proactive engine.

        Returns:
            List of action summary dicts with strategy, targets, type, confidence.
        """
        actions_executed: List[Dict[str, Any]] = []

        for prediction in plan.predictions:
            action_summary = {
                "prediction_id": prediction.prediction_id,
                "strategy": prediction.strategy,
                "target_devices": prediction.target_devices,
                "action_type": prediction.action_type.value,
                "confidence": prediction.confidence,
                "reasoning": prediction.reasoning,
            }
            actions_executed.append(action_summary)

        return actions_executed
