"""Intelligence and reasoning data models."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from src.models.autonomy import ActionType
from src.models.context import ContextSnapshot
from src.models.device import DeviceCommand


@dataclass
class Prediction:
    """A proactive prediction with associated actions."""

    prediction_id: str
    strategy: str  # "pre_cooling", "geyser_preheat", "security_arm", etc.
    target_devices: List[str]
    actions: List[DeviceCommand]
    confidence: float
    action_type: ActionType
    reasoning: str
    estimated_benefit: str


@dataclass
class ActionPlan:
    """A set of predictions generated by the reasoning engine."""

    plan_id: str
    event_id: Optional[str]
    predictions: List[Prediction]
    reasoning_chain: str
    context_snapshot_id: str
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class ReasoningRequest:
    """Request payload sent to the Bedrock reasoning engine."""

    context: ContextSnapshot
    event: Optional[Dict[str, Any]] = None
    preferences: Dict[str, Any] = field(default_factory=dict)
    autonomy_config: Dict[str, int] = field(default_factory=dict)
    query_type: str = "action_plan"  # "action_plan", "explanation", "prediction"


@dataclass
class ReasoningResponse:
    """Response from the Bedrock reasoning engine."""

    actions: List[Dict[str, Any]]
    reasoning_chain: str
    confidence: float
    explanation: str
    latency_ms: int = 0
